// =====================================================================================================================
// = LICENSE:       Copyright (c) 2023 Kevin De Coninck
// =
// =                Permission is hereby granted, free of charge, to any person
// =                obtaining a copy of this software and associated documentation
// =                files (the "Software"), to deal in the Software without
// =                restriction, including without limitation the rights to use,
// =                copy, modify, merge, publish, distribute, sublicense, and/or sell
// =                copies of the Software, and to permit persons to whom the
// =                Software is furnished to do so, subject to the following
// =                conditions:
// =
// =                The above copyright notice and this permission notice shall be
// =                included in all copies or substantial portions of the Software.
// =
// =                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// =                EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// =                OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// =                NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// =                HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// =                WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// =                FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// =                OTHER DEALINGS IN THE SOFTWARE.
// =====================================================================================================================
namespace Kwality.Roslynify.Tests.Generators;

using global::Xunit;

using Kwality.Roslynify.Generators;
using Kwality.Roslynify.Tests.Xunit.Traits.Attributes;

using VerifyCS
    = Kwality.Roslynify.Tests.Generators.Verifiers.CSharpSourceGeneratorVerifier<
        Roslynify.Generators.AutoInterfaceGenerator>;

[SourceGeneratorTest("Auto Interface")]
public sealed class AutoInterfaceGeneratorTests
{
    [Fact(DisplayName = "The \"Marker\" attribute is added unconditionally.")]
    public async Task TheMarkerAttributeIsAddedUnconditionally()
    {
        // ARRANGE / ACT / ASSERT.
        await new VerifyCS.Test
            {
                TestState =
                {
                    Sources =
                    {
                        string.Empty,
                    },
                    ExpectedDiagnostics =
                    {
                        // NOTE: Diagnostics are NOT expected.
                    },
                    GeneratedSources =
                    {
                        // The "Marker" attribute.
                        (typeof(AutoInterfaceGenerator), "Kwality.Roslynify.AutoIAttribute.g.cs", """
                            // <auto-generated />
                            namespace Kwality.Roslynify;

                            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Kwality.Roslynify", "1.0.0.0")]
                            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                            public sealed class AutoInterfaceAttribute : global::System.Attribute
                            {
                                // NOTE: Intentionally left blank.
                            }
                            """),
                    },
                },
            }.RunAsync(CancellationToken.None)
             .ConfigureAwait(false);
    }
}
